# Generated by Django 5.1.7 on 2025-03-16 04:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0002_paciente'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfissionalSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidade', models.CharField(max_length=50)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendamentos.clinica')),
                ('usuario', models.OneToOneField(limit_choices_to={'tipo_usuario': 'M'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField()),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('C', 'Confirmada'), ('R', 'Realizada'), ('X', 'Cancelada')], default='P', max_length=1)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendamentos.clinica')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendamentos.paciente')),
                ('profissional_saude', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendamentos.profissionalsaude')),
            ],
            options={
                'ordering': ['data_hora'],
            },
        ),
    ]
