# Generated by Django 5.1.7 on 2025-03-16 05:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0003_profissionalsaude_consulta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='profissionalsaude',
            name='clinica',
        ),
        migrations.AddField(
            model_name='paciente',
            name='usuario',
            field=models.OneToOneField(default=1, limit_choices_to={'tipo_usuario': 'P'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profissionalsaude',
            name='clinicas',
            field=models.ManyToManyField(to='agendamentos.clinica'),
        ),
        migrations.CreateModel(
            name='Recepcionista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(max_length=200)),
                ('data_contratacao', models.DateField()),
                ('clinicas', models.ManyToManyField(to='agendamentos.clinica')),
                ('usuario', models.OneToOneField(limit_choices_to={'tipo_usuario': 'R'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
