# Generated by Django 5.1.7 on 2025-03-16 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0004_remove_paciente_nome_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='profissionalsaude',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='recepcionista',
            name='usuario',
        ),
        migrations.AddField(
            model_name='paciente',
            name='nome',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='profissionalsaude',
            name='nome',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='recepcionista',
            name='nome',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='clinica',
            name='endereco',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='clinica',
            name='nome',
            field=models.CharField(default='', max_length=100),
        ),
    ]
